### ISSUE TITLE
Blog post

### ISSUE THREAD

**Issue by dabit3** [Microsoft/ReSub#13]
I wrote a yet to be published blog post at https://medium.com/@dabit3/managing-react-state-with-resub-20ea57dee902 and was wondering if someone had some time to review it to make sure I am not misrepresent anything.

Thanks for the library, I'm liking it so far!

**Comment by erictraut** [comment]
Nicely done. Here are a few small comments and suggestions. Feel free to ignore any of these if you think they're off the mark.

* I noticed that you are using yarn rather than npm to install components. Do you think that most readers will already have yarn installed and/or know how to install it? Maybe it has become popular enough at this point to make that assumption.
* Your store is managing two different pieces of data - a text input and the todo list. This would be a great opportunity to demonstrate how to use ReSub trigger keys. You can create one key (any string is fine) for each data type. Then you can modify the trigger calls to specify only the relevant key, and change the autoSubscribe decorators to subscribe to the relevant key. This won't improve performance in your simple example, but in other cases this mechanism can greatly reduce the number of trigger events, and therefore reduce unnecessary state updates and render operations. Then again, maybe you don't want to go into this more advanced topic in your introductory example. It could be a "part 2" of the blog if you see fit to publish a follow-up.
* It's a bit unusual to use a store for a simple text input value. I'd normally just store that in the component state, since its lifetime is limited to that of the component. But for illustration purposes, it's probably fine to keep it in the store. I mention this because some readers might wonder why you're storing it there.
* When you're using TypeScript, it's good form to explicitly mark variables and methods as "private" and "protected" where appropriate. For example, "addTodo" and "updateTextField" should probably be private. (We also use the naming convention that all private variables and methods begin with an underscore, but that's probably not a universal convention.)
* You're declaring your "styles" array as type "any", which throws away all type information. In general, that's not a good idea because you won't get the benefits of type checking. If you move the definition of the object to the top of the file where you currently declare it, TypeScript will automatically infer the types.

**Comment by dabit3** [comment]
Eric! Thank you so much, this was extremely helpful. I appreciate you taking a look and providing such great feedback, and I've gone ahead and updated the post and code to reflect most of these items.

One thing I'm not sure about is if I have  this wired up right, regarding the second point you made (resub trigger keys):

```
import { StoreBase, AutoSubscribeStore, autoSubscribeWithKey } from 'resub'

@AutoSubscribeStore
class TodosStore extends StoreBase {
    private _todos: string[] = ['hello','world']
    private _textInputValue: string = ''

    static AddTodoKey = 'ADDTODOKEY'
    static UpdateTextInputKey = 'UPDATETEXTINPUTKEY'
    
    updateTextInputValue(value: string) {
        this._textInputValue = value;
        this._todos = [...this._todos, 'hellow world adfads']
        this.trigger(TodosStore.UpdateTextInputKey)
    }

    addTodo() {
      if(this._textInputValue === '') return
      this._todos = [...this._todos, this._textInputValue]
      this._textInputValue = ''
      this.trigger(TodosStore.AddTodoKey)
    }

    @autoSubscribeWithKey(TodosStore.AddTodoKey)
    getTodos() {
        return this._todos
    }

    @autoSubscribeWithKey(TodosStore.UpdateTextInputKey)
    getTextInputValue() {
        return this._textInputValue
    }
}

export = new TodosStore()
```

Is this correct, and also do I need to update my App component at all to work with this?

Thanks.

**Comment by berickson1** [comment]
Likewise, as Eric said it looks good!

A couple additional minor comments and suggestions:
**1**
> We call autoSubscribe to make sure that whenever the data changes...

The typescript concept behind how ```@autoSubscribe``` works is called [Decorators](https://www.typescriptlang.org/docs/handbook/decorators.html).  It might be useful to change this to something like the following:

> We add the autoSubscribe decorator to make sure that whenever the data changes...

**2**
Your usage of trigger keys looks good.  We often create a single object that has all the trigger keys.  It only really becomes beneficial to do this when you end up creating manual subscriptions.
```
export const TriggerKeys = {
    InputTextKey: 'input',
    TodosChangedKey: 'todos'
};
```

**3**
Given that there are many different versions of the typescript compiler, you might want to reference a version of the typescript compiler installed in the package scope.
To do this (in npm, I assume yarn is similar), we do the following in package.json.  This allows a developer to run `npm run build` without having any globally installed packages

```
{
  "devDependencies": {
    "typescript": "^2.2.2"
  },

  "scripts": {
    "build": "tsc"
  }
}
```

**Comment by erictraut** [comment]
As Brent said, your use of trigger keys looks correct. There is no need to change anything in your App component.

**Comment by dabit3** [comment]
@berickson1 @erictraut thanks for all of the great feedback!

I've updated the blog post with most of this, and will be publishing on Monday.

If you have any other insight, feel free to share. If not, you're welcome to close this issue.

If I end up doing another post diving deeper into this, I'll be sure to reach back out if that's ok!
