### ISSUE TITLE
[discussion] Update ReSub to support the latest React

### ISSUE THREAD

**Issue by a-tarasyuk** [microsoft/ReSub#78]
The latest version of React _(starting from 16.3.*)_ includes public API changes which will affect on the ReSub in the future.

The following methods will be removed: 
- `componentWillMount`
- `componentWillUpdate`
- `componentWillReceiveProps` - has new _pseudo analog_, `static` method `getDerivedStateFromProps`

In my opinion, the most significant change related to `componentWillMount`, because ReSub uses it to set the initial state., correct me if I'm wrong.

In order to use the latest version of React with **ReSub** would be great to follow new API changes.

Is there any plan/ideas on how to _"smoothly"_ update **ReSub**? Maybe make sense to make all changes and publish major _(for instance 2.0)_ version in order to do not break applications which use the current version of **ReSub**.

What do you think @deregtd @ms-markda @berickson1?

**Comment by deregtd** [comment]
We've had a long series of explorations in anticipation of this.  The big issue is figuring out how to make buildstate work in a similar fashion as it does currently.

Our current thoughts are using getDerivedStateFromProps, and having each component pass a "this" pointer (or an id for a lookup to the this pointer) as initial state, so you can then use getderivedstatefromprops even though it's static, as a non-static.  Super-hacky, but it's very obvious that, for whatever reason, Facebook really doesn't want us doing what we're doing here, so we have to do what we have to do.

Then possibly split buildState into two:  _buildCompleteState, and _buildIncrementalState.  Initial build would run buildcompletestate, and buildincrementalstate would be an optional function that returns Partial<S>.  For back compat, buildstate would map to buildcompletestate, even though the types aren't really correct.

**Comment by erictraut** [comment]
We should try very hard to not make a breaking change to the existing ReSub API. Doing so would require massive changes to existing sources.

We need to find a way to call _buildState some time after the component is constructed (or within the subclass's constructor) and before the component is mounted. Within the new React lifecycle model, is there no callback between the time of construction and the time componentDidMount is called?

When is getDerivedStateFromProps called by the framework? Is that even documented — or something we can rely on? I'm guessing that it's called either before they construct an object instance or within the React.Component constructor. If so, then I don't see a way to make the current buildState work because it assumes it's running within the context of an already-constructed object instance, and we wouldn't be able to call it from getDerivedStateFromProps.

**Comment by deregtd** [comment]
The buildstate split wouldn't be a breaking change, it'd be "use the old or the new, but the new's better".

We need to explore more about the getDerivedStateFromProps call.  I know that @dryganets did investigations here in the past.  Sergei did you ever figure out when it gets called, and if that method works, at least in the current React releases?  I don't know if we'll ever be able to long-term-rely on that timing, but we don't really have a better answer, since we tried working with Facebook and they said they wouldn't support our use case.

**Comment by dryganets** [comment]
I'm going to figure out a solution in a next couple days. React 16.4 already warns about methods usage, I guess we will have 3 different configuration options for different React versions. 

1. As is. for react < 16.3, marked as deprecated
2. Unsafe methods version for react < 17, marked as will be deprecated soon
3. Static life cycle version recommended for usage

I'm going to use 2nd for our upgrade to react-native 0.56 to don't have too many changes and speed up the bump and as a following change - update it to 3rd.

I need to experiment with getDerivedStateFromProps a bit.
If I remember correctly it is called on initial component creation and where componentWillReceiveProps and componentWillMount were called.

My understanding is that the method might be called more frequently than it used to due to the fiber related changes. I'm not sure if this part is already implemented in react. They stated that they are going to apply some optimizations which might cause multiple method calls that's why the original methods got deprecated.

**Comment by deregtd** [comment]
These would be the same style instance methods as _buildState, it just fixes some of the more awkward typings issues that are causing bugs in our codebase periodically.  Even if you mark something non-optional in your State type, if you don't fill it in with the iniitalState build of _buildState, then it's still undefined, and the typing of _buildState lets you do that.  So it'd be better if we enforced an initial whole-build of S, and then had partial-S builds for incremental future updates.

The cunning changes we're talking about involve throwing the this pointer (or an id to a this pointer lookup inside resub) into state, so you can get it out from the static getDerivedStateFromProps, and have that wrap into buildState/buildInitialState/buildInrementalState.

**Comment by dryganets** [comment]
> Do you mean adding UNSAFE_ prefix to componentWillMount, componentWillUpdate componentWillReceiveProps?

No, I mean using super.UNSAFE in the corresponding methods, this should drop the warnings but no more than that.
The real solution will be to move to the newer API.
I think it is going be a breaking change anyway ...

**Comment by a-tarasyuk** [comment]
@dryganets @deregtd @erictraut

Based on the latest **React** changes, `componentWillMount`, `componentWillUpdate` `componentWillReceiveProps` can be replaced only on `getDerivedStateFromProps`.  **React** calls `getDerivedStateFromProps` after `constructor` and before `render`_(on the initial mount and on subsequent updates)_. However there is one issue - it is a `static`., in order to use the current logic need to use some [**hacks**](https://codesandbox.io/s/6ww9rpmmzn), like so

```typescript
constructor(props: P) {
  super(props);
  (this.constructor as any).getDerivedStateFromProps = ComponentBase.getDerivedStateFromProps.bind(this);
 // or
 // ComponentBase.context = this.
}

static getDerivedStateFromProps(props: any, state: any) {
  const context: any = this;
 /**
  * @TODO Handle ReSub logic 
  */
  if (!state) {
    return context._buildInitialState();
  }

  return .....
}
```
However it is more `JavaScript` "way" than `TypeScript`, and in TS there are problems with types. The second way is to move logic to separate class/function which can be used in both static and instance methods, it is basically what [React team recomends](https://reactjs.org/docs/react-component.html#static-getderivedstatefromprops) to do when need to get instance method in `getDerivedStateFromProps` 

> This method doesn’t have access to the component instance. If you’d like, you can reuse some code between getDerivedStateFromProps() and the other class methods by extracting pure functions of the component props and state outside the class definition.

What do you think about the second option? Split general logic to the new module and use it in `ComponentBase`.

**Comment by erictraut** [comment]
Thinking about this more deeply, I don't think ```getDerivedStateFromProps``` will work for resub. The main goal of resub is to automatically track subscriptions. That requires us to associate stores (and keys) with component instances. That means we need a component instance reference at the point the store is called. Since ```getDerivedStateFromProps``` is a static method, ```this``` is not bound to a component instance when it's called, so resub has no way to track the association. 

We may need to rethink the entire idea of subscription auto-tracking. It may not be possible with newer versions of React. My only thought is to leverage ```componentDidUpdate``` to detect props changes after the props have already been updated. This is also inefficient because a props change would call ```componentDidUpdate```, which would then call ```_buildState``` (or whatever new name we'd choose) and then call ```setState``` with the new partial state. This would cause ```componentDidUpdate``` to get called a second time, this time with the same props as before but now with an updated state.

**Comment by dryganets** [comment]
My Idea was to give an unique id to every component and move out the subscription storage to static map. I think it should work. All we need is to save the componentId in the state and later use it to get the subscription context out of the static map.

**Comment by dryganets** [comment]
Initially I thought about saving the 'this' object in the state during the object construction, but I'm affraid it will open the Pandora box as React team is trying to protect us from the future framework changes and by saving the reference to 'this 'I will literally drop the protection layer they created.

**Comment by erictraut** [comment]
That's a clever idea to use the per-instance state to record a unique instance ID.

We could use that same technique to solve the other problem - registering a static method on the subclass that can be called by ComponentBase at the time its ```getDrivedStateFromProps``` is called. We'd probably need to have the base class pass this callback as a parameter to the ComponentBase constructor. 

It would look something like this:

```
class MyComponent extends ComponentBase {
    constructor(props: MyComponentProps) {
        super(props, MyComponent.buildState);
    }

    private static _buildState(props: MyComponentProps, initialBuild: boolean) {
        return {};
    }
}

class ComponentBase {
    constructor(props, buildStateCallback) {
        this.state = _.extend(
             {
                    _componentId: ComponentBase._createUniqueId(),
                    _buildStateCallback: buildStateCallback,
             },
             buildStateCallback(undefined, true)
        );
    }
}
```

This would still be a pretty big breaking change for ReSub consumers because they'd need to:
1. change _buildState to static and pass a reference to it in the constructor.
2. update their logic in _buildState to avoid using any instance variables or methods

**Comment by deregtd** [comment]
Remember you can use .apply to give a new this pointer.

**Comment by dryganets** [comment]
> Remember you can use .apply to give a new this pointer.
Cool idea, thanks, David. 

I re-read the [RFC-06](https://github.com/reactjs/rfcs/blob/master/text/0006-static-lifecycle-methods.md#common-problems), and it sounds like we need to move all our subscribe/unsubscribe logic to the pair componentDidMount/componentWillUnmount anyway.

**Comment by erictraut** [comment]
I didn't come to the same conclusion. They give an example of moving subscribe to componentDidMount, but that doesn't mean it's the only place it can be done. ReSub auto-subscriptions can be applied multiple times without danger of leaks, unlike some subscription mechanisms.

**Comment by a-tarasyuk** [comment]
In my opinion, the following changes in public API look a little bit `"complicated"`

```typescript
class MyComponent extends ComponentBase {
    constructor(props: MyComponentProps) {
        super(props, MyComponent.buildState);
    }

    private static _buildState(props: MyComponentProps, initialBuild: boolean) {
        return {};
    }
}
```

1. Users have to override the `constructor` and pass the reference to `_buildState`, that is not obvious(_can be solved by throwing exception_).

2. In the `_buildState` users cannot use instance helpers to simplify logic inside `_buildState`, and they have to use static methods (about this opportunity was mentioned [here](https://github.com/Microsoft/ReSub/pull/27#issuecomment-341773775), maybe it is not actual anymore, however, for users who use such helpers, need to spend some time to migrate)

```typescript
private static _buildState(props: MyComponentProps, initialBuild: boolean) {
   return { names: MyComponent._buildNames()  };
}
```

If we are talking about changing public API, as there are no good solutions to support current implementation, maybe there are more clear/easy to migrate options. What about to use `decorators? Are there any drawbacks to use them? What do you think?

**Comment by BiggA94** [comment]
Is there any Update on this discussion?

**Comment by deregtd** [comment]
We haven't yet resolved it, unfortunately.  I'm actually planning on spending some time in a couple weeks trying to prototype some solutions and then we'll try to decide what direction to go in.

**Comment by BiggA94** [comment]
I have already done some prototyping see [Pull Request](https://github.com/microsoft/ReSub/pull/118).
I tried not to change the *API* of ReSub.
You cann tell me, what you think about it.
