### ISSUE TITLE
How does this compare to Mobx?

### ISSUE THREAD

**Issue by newtack** [Microsoft/ReSub#8]
Mobx uses a similar approach, what's different?

**Comment by berickson1** [comment]
From looking at the Mobx documentation, it looks like both libraries have taken a slightly different approach to a very similar problem.  When we first started developing ReSub internally, Mobx was not available.

We've chosen the path of fine grain collection of data in a single component state builder function instead of automatic binding of component data.  We liked this since developers can aggregate data from multiple sources and it's easy to see where data is coming from and what will happen on updates at a glance.  This has proven to work well across large datasets from multiple sources for us.

We've also exposed some additional functionality in ReSub to allow more complex patterns like lazy loading & remove data from memory as needed.  User profiles are a good example of this:

Note: the lookup could be to a local datastore, remote service or even another store
```
@AutoSubscribeStore
class UserInfoStore extends StoreBase {

    protected _startedTrackingKey(userId: string) {
        if (this._isPerformingRemoteLookup(userId)) {
            return;
        }

        // Look data up in remote service
        this._performRemoteLookup(userId).then(serviceData => {
            if (!this._isTrackingKey(userId)) {
                return;
            }

            this._userData[userId] = serviceData;
            this.trigger(userId);
        });
    }

    protected _stoppedTrackingKey(phoneNumber: string) {
        // Throw away in-memory data
        this._cancelRemoteLookup(userId);
        delete this._userData[userId];
    }

    @autoSubscribe
    getUserData(@key userId: string): UserData|undefined {
        return this._userData[userId];
    }
}
```

**Comment by newtack** [comment]
Thanks for the clarification

**Comment by phiresky** [comment]
From what I can tell the example above could be accomplished in basically the same way in MobX using Atoms: https://mobx.js.org/refguide/extending.html (which also contains events for starting / stopping an observation)

**Comment by ricklove** [comment]
I think this information would be helpful to add to the documentation (maybe linking to a blog post for details).

Also, it would be interesting to see how this affects build size especially for web apps using ReactXP (compared with using MobX).
